### ISSUE TITLE
Fix NoSQL code

### ISSUE THREAD

**Issue by asfafeeroze** [asfafeeroze/Flight_Roster#1]
Alter layout attribute so that it takes in images -> Currently it's only taking text. 
Add filter search functionalities.

**Comment by nadiaelghouti21** [comment]
the images have been added to the mongodb. for the time being all images are the same. what should be done next is writing a function to so users can add a layout to the database. Working on it :)

**Comment by nadiaelghouti21** [comment]
the uploading image to database issue should be resolved after the commits. we are left with adding filter functionalities.

**Comment by asfafeeroze** [comment]
Please make sure that the modifications for the functions are done in ONE NoSQL code (overwriting the file is okay as long as the code is functional). The data for the collections can be in a different file. 

Also I added a few of the queries and updated the main.py with them so you and Yasemin can add on the rest. :)
